version: "3.1"
services:
    php-fpm:
      build: docker/php-fpm
      container_name: terry_api
      working_dir: /app
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

