version: "3.1"
services:
    php-fpm:
      build: docker/php-fpm
      container_name: terry_api
      working_dir: /app
      env_file:
        - ./docker/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

