version: "3.1"
services:
    php-fpm:
      build: docker/php-fpm
      container_name: terry_api
      working_dir: /app
      env_file:
        - ./docker/php-fpm/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
